### ISSUE TITLE
Parcey doesn't compile with a recent ceylon from Git

### ISSUE THREAD

**Issue by jpragey** [renatoathaydes/parcey#1]
The faulty line is in `combinators.ceylon` line 67:

``` ceylon
            } else if (is ParseError result) {
```

which IMHO should be:

``` ceylon
            } else if (is ErrorMessage result) {
```

`ceylon doc`doesn't work neither, but I bet it's a ceylon PB.

**Comment by renatoathaydes** [comment]
@jpragey Thanks for letting me know!
