### ISSUE TITLE
support 1.2.0 in herd ?

### ISSUE THREAD

**Issue by vietj** [renatoathaydes/parcey#2]
In this planned ?

**Comment by renatoathaydes** [comment]
I need to finish replacing the StringBuilder extremely slow character consumer with something fast... when I finish that , I will publish on Herd!

**Comment by renatoathaydes** [comment]
I'm done with the new code, but can't release it as I got affected by this horrible [Ceylon bug](https://github.com/ceylon/ceylon/issues/5855). 

I can't find an easy workaround so I will just park development of this lib for now. Sorry about that.

**Comment by renatoathaydes** [comment]
Version 0.3.0 is on Herd now.
